const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {Store}=require('../src/store.cjs'),{Providers}=require('../src/providers.cjs'),{emptyState}=require('../src/core.cjs');
const response=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers});
async function fixture(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'deck-lab-test-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));return new Store(dir);}
test('atomic local persistence survives reload and rejects invalid replacement',async t=>{const store=await fixture(t);await store.save(emptyState());const s=emptyState();s.hidden=['TCG|Test'];await store.save(s);assert.deepEqual((await new Store(store.directory).load()).hidden,s.hidden);await assert.rejects(store.save({schema:2}));assert.deepEqual((await store.load()).hidden,s.hidden);});
test('cache fallback preserves source timestamp and exposes network failure',async t=>{const store=await fixture(t);await store.write('cards-cache.json',{checked:1,data:[{id:'1'}]});const p=new Providers(store,async()=>{throw Error('Offline');});const result=await p.cards();assert.equal(result.checked,1);assert.equal(result.warning,'Offline');assert.equal(result.data[0].id,'1');});
test('Master Duel exhausts short pages and rejects repeated pages',async t=>{const store=await fixture(t);await store.write('cards-cache.json',{checked:Date.now(),data:[]});let requests=0;const raw={_id:'one',created:'2026-01-02T00:00:00Z',deckType:{_id:'x',name:'Test'},main:[{card:{name:'Alpha'},amount:3}]};const p=new Providers(store,async()=>response(requests++===0?[raw]:[]));const s=await p.decks({format:'Master Duel',type:{id:'x',name:'Test'},from:'2026-01-01',to:'2026-01-03'});assert.equal(s.decks.length,1);assert.equal(requests,2);const repeated=new Providers(store,async()=>response([raw]));await assert.rejects(repeated.decks(s.query),/repeated/);});
test('other format queries reject mixed-format data',async t=>{const store=await fixture(t);await store.write('cards-cache.json',{checked:Date.now(),data:[]});const p=new Providers(store,async()=>response([{deckNum:1,format:'Master Duel Decks'}]));await assert.rejects(p.decks({format:'TCG',type:{id:'all'},from:'2026-01-01',to:'2026-01-02',tier:'any'}),/outside/);});
test('403 cooldown stops repeat requests',async t=>{const store=await fixture(t);let calls=0;const p=new Providers(store,async()=>{calls++;return response({},403);});await assert.rejects(p.priceRequest('/test'),/403/);await assert.rejects(p.priceRequest('/test'),/paused/);assert.equal(calls,1);});
test('429 long Retry-After does not immediately retry',async t=>{const store=await fixture(t);let calls=0;const p=new Providers(store,async()=>{calls++;return response({},429,{'retry-after':'120'});});await assert.rejects(p.priceRequest('/test'),/429/);assert.equal(calls,1);assert(p.blockedUntil-Date.now()>115000);});
test('verified low excludes wrong condition, seller and stock',async t=>{const store=await fixture(t);const base={productId:10,listingId:1,verifiedSeller:true,language:'English',condition:'Near Mint',printing:'1st Edition',quantity:1,price:1.5,sellerName:'Fixture'};const listings=[base,{...base,listingId:2,price:.01,verifiedSeller:false},{...base,listingId:3,price:.02,condition:'Damaged'},{...base,listingId:4,price:.03,quantity:0},{...base,listingId:5,price:1.2}];const p=new Providers(store,async()=>response({results:[{results:listings,totalResults:listings.length}]}));const q=await p.quote({product:{id:10},condition:'Near Mint',edition:'1st Edition'});assert.equal(q.cents,120);assert.equal(q.verified,true);});
test('concurrent pricing requests are serialized',async t=>{const store=await fixture(t);let active=0,max=0;const p=new Providers(store,async()=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,10));active--;return response({});});await Promise.all([p.priceRequest('/one'),p.priceRequest('/two'),p.priceRequest('/three')]);assert.equal(max,1);});
